[workspace]
members = [
    "crates/artemis-core",
]
resolver = "2"

[workspace.dependencies]
##alloy
alloy = { version = "0.11.1", features = ["full", "providers", "rpc"] }
alloy-node-bindings = { version = "0.11.1" }

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'
