[workspace]
members = [
    "crates/artemis-core",
]
resolver = "2"

[workspace.dependencies]
##alloy
alloy = { version = "0.9.2", features = ["full"] }
alloy-node-bindings = { version = "0.9.2" }

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'
